### PR TITLE
Before I get carried away i'm pull requesting this

### LINKED ISSUE #52: Fix the inventory table in the database
Currently most of the items in the inventory have names that are capitalized. This makes searching difficult because the user has to type exactly how it is in the db. We need to either change all the names to lowercase in the db or change the search query or endpoints to manipulate the user input so it will match what is in the db.

### LINKED ISSUE #65: Checkout Button Doesn't work
Checkout Button Doesn't work anymore on the pos page. (Just needs an `<a>` tag in the button)

### PR DESCRIPTION
**Pull request by calvinbrown085**
closes #52 
closes #65

### CODE REVIEW

**Comment by ethanphunter** [comment]
Looks good as far as I can tell without running it myself. :+1:

**Comment by calvinbrown085** [comment]
it works :)

**Comment by calvinbrown085** [comment]
Can we please merge this

**Comment by ethanphunter** [comment]
:+1:

**Comment by ethanphunter** [comment]
@calvinbrown085 Merge conflicts here

**Comment by calvinbrown085** [comment]
@ethanphunter fixed

**Comment by ethanphunter** [comment]
Merging once builds are green

**Comment by ethanphunter** [comment]
Merging....

**Comment by calvinbrown085** [comment]
👍

**Pull request merged**
