### PR TITLE
Added a generate report endpoint that gives back product id name and …

### LINKED ISSUE #44: Create report endpoints
We need to create endpoints that provide data from the database. At least in CSV if not Json as well.

### LINKED ISSUE #47: Inventory Changes
It would probably look better if the inventory table had headers for each of the columns. Currently, the html is a bit messy and only has a "name" row on it that's not even in the table....

### PR DESCRIPTION
**Pull request by calvinbrown085**
…how much they made off of the product in a csv format
closes #44
closes #47 also

### CODE REVIEW

**Comment by ethanphunter** [comment]
:+1:

**Comment by ethanphunter** [comment]
:+1: again

**Comment by calvinbrown085** [comment]
@ethanphunter Fixed

**Comment by ethanphunter** [comment]
:smile: :+1:

**Pull request merged**
