### PR TITLE
Added the ability for the manager to update or add a new item to the …

### PR DESCRIPTION
**Pull request by calvinbrown085**
…inventory via the manager page

### CODE REVIEW

**Comment by ethanphunter** [comment]
@calvinbrown085 Could you give some more context on this?

**Comment by ethanphunter** [comment]
Like, what does the `/managerUpdate` endpoint do?

**Comment by calvinbrown085** [comment]
image

**Comment by ethanphunter** [comment]
:+1:

**Comment by gilmerc** [comment]
:+1:

**Comment by ethanphunter** [comment]
@calvinbrown085 Merge conflicts here again...............

**Comment by calvinbrown085** [comment]
@ethanphunter fixed

**Pull request merged**
