### PR TITLE
Added files for our web request

### PR DESCRIPTION
**Pull request by calvinbrown085**

### CODE REVIEW

**Comment by ethanphunter** [comment]
Needs to have *.pyc added to `.gitignore`

**Comment by ethanphunter** [comment]
@calvinbrown085 Do we want to merge this?

**Comment by calvinbrown085** [comment]
@ethanphunter we don't have too, it doesn't matter to me

**Comment by calvinbrown085** [comment]
@ethanphunter i'm just going to merge this

**Pull request merged**
