### PR TITLE
Insert intodatabase

### LINKED ISSUE #24: Have API Grab Inventory Info

### LINKED ISSUE #33: Be able to insert stuff into the database

### PR DESCRIPTION
**Pull request by calvinbrown085**
…ode, gets the stuff for the inventory
closes #33 
closes #24 
please merge the other pull request first

### CODE REVIEW

**Comment by ethanphunter** [comment]
I'll move my comment over here.

**Comment by ethanphunter** [comment]
@calvinbrown085 Has this been tested? My only concern is the connections to the database. I don't know what is better, this or making a class so that we have more control over the connections to the database. I don't know how this code would run, I think it could potentially slow down the first query.

**Comment by ethanphunter** [comment]
Also this isn't dependent on any other prs now is it?

**Comment by calvinbrown085** [comment]
@ethanphunter I'm gonna ping you on slack is that fine?

**Comment by calvinbrown085** [comment]
@ethanphunter changed that

**Comment by ethanphunter** [comment]
Sorry about being kinda picky. :) :+1:

**Comment by calvinbrown085** [comment]
@ethanphunter no biggie, I would rather have it right than half right :smile:

**Pull request merged**
