### PR TITLE
Added a lot of inventory to the one off script

### PR DESCRIPTION
**Pull request by calvinbrown085**

### CODE REVIEW

**Comment by maceroni** [comment]
:+1:

**Comment by ethanphunter** [comment]
The endpoint in here needs to be protected using `requireLogin()` at the beginning of the endpoint function which is added here: https://github.com/ethanphunter/PointOfSaleProject/pull/37

**Comment by ethanphunter** [comment]
:+1:

**Comment by ethanphunter** [comment]
@calvinbrown085 We either need to put `requireLogin` on the endpoint, or just run this locally and remove the endpoint before this gets merged.

**Comment by calvinbrown085** [comment]
@ethanphunter i'll just run locally, i'm not able to grab the prod db though

**Comment by ethanphunter** [comment]
:+1:

**Comment by calvinbrown085** [comment]
@ethanphunter I'm just gonna merge this since its already been run

**Pull request merged**
